{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bba5bd84",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Q1\n",
    "import requests\n",
    "import requests\n",
    "\n",
    "url=\"https://jsonplaceholder.typicode.com/posts \"\n",
    "data={\n",
    "    \"title\":\"my first post\",\n",
    "    \"body\":\"this is my first api request\",\n",
    "    \"userid\":1\n",
    "}\n",
    "response=requests.post(url,json=data)\n",
    "print(\"status code:\",response.status_code)\n",
    "print(\"response json\")\n",
    "print(response.json())\n",
    "\n",
    "#Q2\n",
    "import requests\n",
    "url=\"https://jsonplaceholder.typicode.com/posts\"\n",
    "playlist_name=input(\"enter your playlist name\")\n",
    "playlist_description=input(\"enter your playlist description\")\n",
    "data={\n",
    "    \"title\":\"playlist name\"\n",
    "    \"body\":\"playlist descripition\"\n",
    "    \"userid\":1\n",
    "\n",
    "}\n",
    "response=requests.post(url,json=data)\n",
    "result=response.json()\n",
    "print(\"\\nplaylist created succesfully\")\n",
    "print(\"playlist id:\",result[\"id\"])\n",
    "\n",
    "#Q3\n",
    "import requests\n",
    "url=\"https://reqres.in/api/users\"\n",
    "data={\n",
    "    \"name\":\"prachi\",\n",
    "    \"job\":\"student\"\n",
    "}\n",
    "response=requests.url(data,json=data)\n",
    "result=response.json()\n",
    "print(\"status code:\",response.status_code)\n",
    "print(\"user id:\",result[id])\n",
    "print(\"created at:\",result[\"createdAt\"])\n",
    "\n",
    "#Q4\n",
    "import requests\n",
    "import csv\n",
    "url=\"https://jsonplaceholder.typicode.com/posts\"\n",
    "response=requests.get()\n",
    "posts=response.json()[:5]\n",
    "with open(\"posts.csv\",\"w\",newline=\"\",encoding=\"UTF-8\")as file:\n",
    "    writer=csv.writer(file)\n",
    "    writer.writerow(\"title\",\"user id\")\n",
    "    for post in posts:\n",
    "        writer.writerow([post[\"title\"],post[\"user id\"]])\n",
    "print(\"posts.csv created successfully\")\n",
    "\n",
    "#Q5\n",
    "import requests\n",
    "import json\n",
    "url=\"https://jsonplaceholder.typicode.com/posts\"\n",
    "response=requests.get(url)\n",
    "posts=response.json()[:5]\n",
    "with open(\"posts.json\",\"w\",encoding=\"UTF-8\")as file:\n",
    "    json.dump(posts,file,indent=4)\n",
    "print(\"posts.json created succesfully\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
